version: '3.7'

services:
  proxy:
    image: nginx:alpine
    container_name: proxy
    ports:
      - '3000:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: 'unless-stopped'
    networks:
      - playlist
  server:
    build:
      context: ./
      target: production-build-stage
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '3000'
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - playlist
    links:
      - postgres
    depends_on:
      - postgres
  postgres:
    image: postgres:14.6
    container_name: postgresql
    environment:
      POSTGRES_DB: music_playlist
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - '5432'
    networks:
      - playlist

networks:
  playlist:
    name: playlist
    driver: bridge

volumes:
  data:
    driver: local


# docker exec -it server sh -c "npm run migrate"
# docker exec -it server sh -c "npm run seed"
# docker exec -it server sh -c "npm run rollback"